/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { WithoutDto } from "./WithoutDto";
import { WithoutDtoCountArgs } from "./WithoutDtoCountArgs";
import { WithoutDtoFindManyArgs } from "./WithoutDtoFindManyArgs";
import { WithoutDtoFindUniqueArgs } from "./WithoutDtoFindUniqueArgs";
import { DeleteWithoutDtoArgs } from "./DeleteWithoutDtoArgs";
import { WithoutDtoService } from "../withoutDto.service";
@graphql.Resolver(() => WithoutDto)
export class WithoutDtoResolverBase {
  constructor(protected readonly service: WithoutDtoService) {}

  async _withoutDtosMeta(
    @graphql.Args() args: WithoutDtoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [WithoutDto])
  async withoutDtos(
    @graphql.Args() args: WithoutDtoFindManyArgs
  ): Promise<WithoutDto[]> {
    return this.service.withoutDtos(args);
  }

  @graphql.Query(() => WithoutDto, { nullable: true })
  async withoutDto(
    @graphql.Args() args: WithoutDtoFindUniqueArgs
  ): Promise<WithoutDto | null> {
    const result = await this.service.withoutDto(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WithoutDto)
  async deleteWithoutDto(
    @graphql.Args() args: DeleteWithoutDtoArgs
  ): Promise<WithoutDto | null> {
    try {
      return await this.service.deleteWithoutDto(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
